### ISSUE TITLE
KNL

### ISSUE THREAD

**Issue by jeffhammond** [flame/blis#102] opened 2016-10-21 23:29 UTC
This issue is for https://github.com/devinamatthews/blis/tree/knl but @devinamatthews has issues disabled there.

It seems that threading (OpenMP and POSIX) is not support for KNL.  Why?  Can't you reuse the threading code for other Intel targets?

```
[jrhammo@node07 git]$ ./configure --enable-threading=openmp --enable-cblas --enable-blas --enable-verbose-make --enable-shared --enable-static  CC=icc knl
configure: checking whether we need to update the version file.
configure: checking version file './version'.
configure: found '.git' directory; assuming git clone.
configure: executing: git describe --tags.
configure: got back 0.2.0-102-gc8e4ef9.
configure: truncating to 0.2.0-102.
configure: updating version file './version'.
configure: starting configuration of BLIS 0.2.0-102.
configure: manual configuration requested.
configure: configuring with 'knl' configuration sub-directory.
configure: no install prefix given; defaulting to '/home/jrhammo/blis'.
configure: debug symbols disabled.
configure: enabling verbose make output, disable with 'make V=0'.
configure: building BLIS as a static library.
configure: building BLIS as a shared library.
Unsupported threading model: openmp.
[jrhammo@node07 git]$ make -j64
cat: /version: No such file or directory
make: Warning: File `common.mk' has modification time 28667 s in the future
Makefile:435: *** Cannot proceed: config.mk not detected! Run configure first.  Stop.
```

**Comment by chipbuster** [comment] 2016-10-24 21:02
I've found that using `--enable-threading=omp` instead of `--enable-threading=openmp` seems to convince it to work, not sure if that's intended behavior or not.

**Comment by devinamatthews** [comment] 2016-10-24 21:06
@jeffhammond if you know how to enable issues on a fork I'll turn it on, but here is OK I guess.

**Comment by devinamatthews** [comment] 2016-10-24 21:08
Ah, I haven't merged whatever commit in BLIS changed "omp" to "openmp". Note that there is a comment in the configure output: `Unsupported threading model: openmp.`. The current appropriate option should be documented by `configure --help`.

**Comment by fgvanzee** [comment] 2016-10-24 21:45
Yes, apologies for this inconvenience, folks. I made the change not because it "needed" to be done, but I thought that stylistically "openmp" (versus "omp") was the textual analogue to "pthreads".

**Comment by jeffhammond** [comment] 2016-10-24 22:43
@devinamatthews Unnecessarily pedantic answer to question below 😉 

![help-devin](https://cloud.githubusercontent.com/assets/406118/19666625/85754204-9a00-11e6-9901-05c52bb6247d.png)

**Comment by jeffhammond** [comment] 2016-10-24 22:46
@devinamatthews @fgvanzee Is there any reason not to support `{openmp,omp}` and `{pthread,pthreads,posix}` case-insensitively, to minimize the possibility of failure?

IBM Blue Gene MPI parsed `{DCMF_INTERRUPT,DCMF_INTERRUPTS,DCMF_INTERUPT,DCMF_INTERUPTS}` and similar wherever spelling might be an issue, which I always felt was a particularly wise decision.  It prevented many instances of "WTF was that environment variable called again?" 😃

**Comment by fgvanzee** [comment] 2016-10-24 22:51
@jeffhammond While we're at it, why not just overload every standard C library function with every possible misspelling of the function name? Oh, because then we would have no more use for man pages! Can't let that happen. :)

I think it's reasonable for a user to not know about a feature unless/until they read about it, and when they read about it (via `--help`, for example) they will see the expected syntax. Am I being boring and unreasonable here? ;)

**Comment by jeffhammond** [comment] 2016-10-25 18:12
Note that this ticket exists because I did exactly as you suggested but the
implementation didn't match the documentation.

The standards to which we hold developers is different than that of users.
I don't expect you to think like a user, but that's why I'm here :wink:

-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by devinamatthews** [comment] 2016-10-25 18:15
KNL isn't in the main tree yet. Try the 'knl' branch of devinamatthews/blis.

**Comment by devinamatthews** [comment] 2016-10-25 18:26
I'm actually with Jeff on this one. I'll submit a PR tomorrow. Also, it 
might be better if threading were the default (thoughts?)

**Comment by devinamatthews** [comment] 2016-10-25 18:38
To be pedantic, the documentation (./configure --help) for the knl 
branch in devinamatthews/blis *does* say "omp", not "openmp", but I am 
working on merging that into flame:master so that problem will go away.

**Comment by fgvanzee** [comment] 2016-10-25 18:43
I think I only followed about 70% of this thread. (Still don't understand Jeff's screenshot.) But I'm going to assume everything is taken care of now or will be soon.

**Comment by jeffhammond** [comment] 2016-10-25 19:01
Field: screenshot was because Devin didn't know how to enable issues on his
fork.



-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by devinamatthews** [comment] 2016-10-25 19:06
KNL PR (#105) is submitted, so I think we can close this.

**Comment by fgvanzee** [comment] 2016-10-25 19:10
@jeffhammond Ah, thanks, I couldn't connect the dots. Or, red boxes.

**Closed** 2016-10-25 22:15 UTC
