### ISSUE TITLE
Benchmarks: environment variable for MKL performance

### ISSUE THREAD

**Issue by bartoldeman** [flame/blis#312] opened 2019-05-14 17:14 UTC
In,
https://github.com/flame/blis/blob/master/docs/Performance.md
I noticed that MKL on EPYC was abysmal, but that's just because it uses SSE2 on AMD by default.
You can set the following (undocumented!) environment variable to tell MKL to use AVX2 CPU instructions:
export MKL_DEBUG_CPU_TYPE=5

**Comment by fgvanzee** [comment] 2019-05-14 19:15
Hi @bartoldeman. Thanks for your feedback and your interest in BLIS.

I've heard rumblings of this "magic" environment variable one could set on AMD Ryzen/Epyc systems that would cause MKL to choose the correct kernels, and so it's good to hear it confirmed by others.

That said, I don't plan on updating the Epyc benchmarks to reflect the use of `MKL_DEBUG_CPU_TYPE=5` for two (somewhat related) reasons.

The first reason is that, as you said, use of this environment variable is an undocumented trick. Documented vs undocumented capabilities is a very convenient boundary at which to draw the line between what is reasonable to expect a typical user to be able to figure out and execute, and what is unreasonable. (In fairness, I similarly would not consider including performance results from BLIS in the [Performance](https://github.com/flame/blis/blob/master/docs/Performance.md) document using an undocumented feature.)

The second and perhaps more important reason: Executives at Intel clearly do not currently **want** MKL to perform well on AMD hardware; if they did, they would have already inserted relatively straightforward code that correctly parsed the vendor string from the `CPUID` instruction and activated the appropriate kernels accordingly. If and when Intel changes this implicit policy and updates MKL to properly choose kernels on AMD hardware, I will be happy to perform the experiments again.

**Comment by ValZapod** [comment] 2019-11-27 01:34
@fgvanzee I think you should reconsider https://www.reddit.com/r/matlab/comments/dxn38s/howto_force_matlab_to_use_a_fast_codepath_on_amd/

and least run some tests, you know, to check bitexact propeties.

**Comment by wickeat** [comment] 2020-07-16 08:59
It's worth noting that in the latest Update 1 2020 (mkl/19.1.1), the workaround does not work anymore.

https://kb.hlrs.de/platforms/index.php/Libraries(Hawk)

**Comment by fgvanzee** [comment] 2020-07-16 14:42
@wickeat Thank you for pointing this out. The workaround's potential (and now confirmed) transience is yet another reason why nobody should have relied on it for performance measurement in the first place.

**Comment by bartoldeman** [comment] 2020-07-16 16:20
The newest MKL has a `mkl_blas_def_dgemm_kernel_zen` symbol which seems to be responsible, ie. they actually seem to support Zen but it doesn't work as well as "Intel" avx2 -- it's about 12.5% slower on a dual socket AMD 7452 (64 cores total) with HPL.

FWIW AMD BLIS was very close in my HPL tests on the same chip, within 3% of the old MKL with the workaround.

**Comment by fgvanzee** [comment] 2020-07-16 16:48
> The newest MKL has a `mkl_blas_def_dgemm_kernel_zen` symbol which seems to be responsible, ie. they actually seem to support Zen but it doesn't work as well as "Intel" avx2 -- it's about 12.5% slower on a dual socket AMD 7452 (64 cores total) with HPL.

@bartoldeman I'm not surprised that Intel doesn't want their HPC product to perform perfectly on a competitor's microarchitecture since it risks the situation where a purchasing manager can justify the switch to more cost-effective AMD hardware (while not sacrificing any performance out of one of their users' favorite tools).

**Comment by devinamatthews** [comment] 2020-08-06 21:01
Intel giveth and Intel taketh away, so I am closing.

**Closed by devinamatthews** 2020-08-06 21:01 UTC
