### ISSUE TITLE
typo in edge case handler

### ISSUE THREAD

**Issue by moon-chilled** [flame/blis#624] opened 2022-03-30 06:38 UTC
In [bli_edge_case_defs.h:50](https://github.com/flame/blis/blob/master/frame/include/bli_edge_case_macro_defs.h#L50):

```c
	PASTEMAC(ch,ctype)           _ct[ BLIS_STACK_BUF_MAX_SIZE / sizeof( PASTEMAC(ch,type) ) ] \
```

I think it should be `sizeof( PASTEMAC(ch,ctype) )` (note **c**type, not type).

**Comment by fgvanzee** [comment] 2022-09-10 21:40
@moon-chilled I have no idea how this issue went un-addressed by one of us for this long. Please accept my apologies. I'm looking into this now.

**Comment by fgvanzee** [comment] 2022-09-10 21:54
@devinamatthews This is bad. I'm not sure if it's causing us any issues, but it's a buffer overrun waiting to happen.

The problem is that `GEMM_UKR_SETUP_CT_PRE` uses `sizeof( PASTEMAC(ch,type) )`.

Presumably, you intended this to evaluate to expressions such as `sizeof( double )`. But the `bli_dtype` macro is defined as `BLIS_DOUBLE`. I'm guessing `sizeof()` an `enum` value will be equivalent to `sizeof( int )`, which will be too small in all cases except for the `s`/`float` case.

**Comment by fgvanzee** [comment] 2022-09-10 21:57
I now realize that because the malformed expression is in the denominator, it means we're getting *too many* elements, not too few. Whew.

**Comment by fgvanzee** [comment] 2022-09-13 16:47
@moon-chilled I've applied your fix. Please re-open this issue if you have any further related concerns. Thanks again for your feedback.

**Closed by fgvanzee** 2022-09-13 16:47 UTC
