### ISSUE TITLE
Poor dgemm scaling with number of threads

### ISSUE THREAD

**Issue by bandokihiro** [flame/blis#644] opened 2022-07-14 16:14 UTC
I have an application in which I do relatively large dgemm of particular shapes using multi-threaded BLAS implementations on CPUs. I am interested in getting good performance on AMD Epyc 7742 64-core processors. Based on my research, the blis library provides the highest performance and I have reproduced the results for square dgemm in the wiki (see plot below). The command line I used for this is 
```
OMP_NUM_THREADS=64 OMP_PROC_BIND=true numactl --interleave 0-3 --physcpubind 0-63 -- ./a.out
```
![Figure 1](https://user-images.githubusercontent.com/39278362/179026419-336f4296-46de-4a93-92de-9a5239312971.png)

Now my application doesn't scale well with the number of threads. I investigated this, using the same kind of benchmark, how dgemm scales for the particular shapes my application uses. The scaling plot is found below:
![AMDRome_benchmark_solver_gemm](https://user-images.githubusercontent.com/39278362/179026754-dfb09482-1443-4538-afaa-bab0e8e232d1.png)
The same command line was used and the value of the env variable `OMP_NUM_THREADS` was varied. I wanted to know if this looks normal and, if not, how I can improve this. The shapes of the matrices are a small operator matrix on the left and a fat matrix on the right. Below are the exact shapes ((M,K,N) for MxK x KxN):
```
0: 125,125,320000
1: 375,125,320000
2: 125,375,320000 (left is transposed)
3: 150,125,320000
4: 450,125,320000
5: 125,150,320000 (left is transposed)
6: 125,450,320000 (left is transposed)
```
Thank you very much for your help.

**Comment by devinamatthews** [comment] 2022-07-14 17:00
What are the storage formats of the A, B, and C matrices (row- or column-major)? Certain combinations will lead to sub-optimal performance due to the storage preference of the microkernel and the way the algorithm is structured.

**Comment by bandokihiro** [comment] 2022-07-14 17:02
A, B, and C are all row major.

**Comment by devinamatthews** [comment] 2022-07-14 17:04
Yup. m << n with row-major C is the problem case. If you can switch C to column-major that might be a quick fix. Longer-term we need to add some additional flexibility to the algorithm for non-square GEMMs.

**Comment by devinamatthews** [comment] 2022-07-14 17:05
If you would like to participate in an experiment I can make you a branch to try with some modifications.

**Comment by bandokihiro** [comment] 2022-07-14 23:48
![AMDRome_benchmark_solver_gemm_blis_LayoutLeft](https://user-images.githubusercontent.com/39278362/179119555-e98fa652-0c42-4181-87c6-6913c9689d4c.png)
The numbers in column-major setting.

**Comment by devinamatthews** [comment] 2022-07-16 16:35
Definitely looks better. Your problems are probably somewhat memory-bound so you may not be able to do better. I'll try and set up a branch for you try test out early next week.

**Comment by bandokihiro** [comment] 2022-07-16 19:41
Thanks. Is your experiement something that you expect you will be able to stably merge into master relatively easily? If your changes allow me to get the same kind of performance with a row-major ordering, I would hold off making a bunch of changes in my code to make the layout change.

**Comment by devinamatthews** [comment] 2022-07-18 18:52
@bandokihiro I will make branch(es) after meeting with @fgvanzee tomorrow. I want to make sure I test things which can potentially be incorporated into the master branch. Do note that it might take some time to get merged since we will have to do additional benchmarking etc. Thanks for the bug report and your willingness to be a guinea pig.

**Comment by devinamatthews** [comment] 2022-07-19 19:27
@bandokihiro what version of BLIS are you using now?

**Comment by devinamatthews** [comment] 2022-07-19 20:59
@bandokihiro please try the branch `gemmsup-bp-flip`. If you could run both row- and column-major experiments that should provide some valuable information.

**Comment by bandokihiro** [comment] 2022-07-19 21:02
I am on the latest tag so 0.9.0. I'll try to run this today, thanks.

**Comment by bandokihiro** [comment] 2022-07-20 00:18
![figure](https://user-images.githubusercontent.com/39278362/179869294-56ffd2e9-1821-4837-81b8-53a49adb5bcb.png)
column-major / row-major

row-major improved but column-major's performance degraded

**Comment by devinamatthews** [comment] 2022-07-21 16:01
@bandokihiro to that purpose, would you mind sharing your microbenchmark code?

**Comment by bandokihiro** [comment] 2022-07-21 16:07
I am using kokkos-kernels, which redirects the dgemm calls to third-party libraries. I don't interface with blis directly. The layout is controlled by a simple template argument of Kokkos views. I think the way it works under the hood is that the redirection is successful when the layouts of A, B, and C match. For one of them (column or row-major), all matrices are tranposed in the call to the library.  Is that still of interest to you?

**Comment by devinamatthews** [comment] 2022-07-21 16:10
OK, I can write my own pretty easily.

**Comment by devinamatthews** [comment] 2022-07-22 19:49
@bandokihiro I was able to reproduce your performance graphs and do some additional experiments. I *think* we've found a simple solution which increases the performance of the row-major case so that it is similar to the column-major case. However we need to check that it doesn't have any unintended consequences.

**Comment by bandokihiro** [comment] 2022-07-22 19:59
Great, thank you very much! Let me know when I can try.

**Comment by devinamatthews** [comment] 2022-07-26 21:48
@bandokihiro please try the `gemmsup-kc0` branch. If this gives good performance for both storage formats then we can go ahead and merge.

**Comment by bandokihiro** [comment] 2022-07-27 03:21
It looks pretty good. This figure summarizes all results. Left is column-major, right is row-major:
![figure](https://user-images.githubusercontent.com/39278362/181153597-c8301776-7026-4481-b9b3-0d64f6c52901.png)

**Closed** 2022-07-27 18:54 UTC

**Comment by fgvanzee** [comment] 2022-07-28 15:13
Glad we were able to accomodate you on this, @bandokihiro. Thank you for helping @devinamatthews zero in on a solution.

**Comment by bandokihiro** [comment] 2022-07-28 15:23
No problem. Thank you very much for your assistance.
