### ISSUE TITLE
BG/Q support

### ISSUE THREAD

**Issue by chiensh** [flame/blis#222] opened 2018-06-19 11:42 UTC
may I confirm that  BGQ is no longer supported by BLIS? 

I cannot find the announcement of discontinued support of this platform, but no matter how hard I change the configure and all related .mk files, the latest master cannot be compiled by bgxlc anymore.  (I managed to compile version 0.2.2. before, although it did not work correctly)

**Comment by fgvanzee** [comment] 2018-06-19 16:52
@chiensh Sorry to hear about your troubles with the `bgq` configuration. As Jeff mentioned, we don't have access to the hardware (and we are short on BG/Q expertise). If you can provide more details, we (mostly Jeff) might be able to help you out.

@jeffhammond Thanks for volunteering to look into this.

**Comment by jeffhammond** [comment] 2020-01-03 21:59
I am closing this issue because ALCF Blue Gene/Q systems have been [retired](https://www.alcf.anl.gov/news/argonne-s-mira-supercomputer-set-retire-after-years-enabling-groundbreaking-science) and thus friends of BLIS like me lack the ability to reproduce user errors.

**Closed by jeffhammond** 2020-01-03 21:59 UTC
