### ISSUE TITLE
gcc minimum version needs increasing for x86

### ISSUE THREAD

**Issue by loveshack** [flame/blis#324] opened 2019-08-20 13:49 UTC
The gcc 4.7+ requirement in configure needs to be increased.  I don't know when they were introduced, but -march=sandybridge and haswell aren't supported in gcc 4.8 (EL7).

**Comment by fgvanzee** [comment] 2019-08-20 17:41
Thanks, Dave. I'm fine with bumping the minimum gcc version to 4.8.

**Comment by fgvanzee** [comment] 2019-08-20 17:44
@loveshack Sorry, I misread your comment. I thought you were saying that the aforementioned flag syntax wasn't supported *until* version 4.8. I'll try to dig into this to see if I can find out when gcc switched their `-march` syntax.

**Comment by fgvanzee** [comment] 2019-08-20 17:54
Here's what I found in the [gcc documentation](https://gcc.gnu.org/onlinedocs/): 
- As of gcc version [4.8.5](https://gcc.gnu.org/onlinedocs/gcc-4.8.5/gcc/i386-and-x86-64-Options.html#i386-and-x86-64-Options), the syntax for `-march` was still using the awful `corei7-avx`, `core-avx-i`, `core-avx2` labels.
- As of gcc version [4.9.4](https://gcc.gnu.org/onlinedocs/gcc-4.9.4/gcc/i386-and-x86-64-Options.html#i386-and-x86-64-Options), the syntax for `-march` had transitioned to accepting (and promoting the use of) `sandybridge`, `ivybridge`, `haswell` labels.

So presumably the switchover happened sometime between those two versions.

Whether we draw the line at 4.7, 4.8, or 4.9.x doesn't matter to me--they're all ancient. So I'm fine bumping the minimum required version to 4.9.4. 

What do you think, @devinamatthews?

**Comment by devinamatthews** [comment] 2019-08-20 18:12
This depends on whether you want to support system compilers or assume that people will get a newer version through some mechanism. For example, CentOS 7 is still using gcc 4.8.5.

**Comment by fgvanzee** [comment] 2019-08-20 18:32
Thanks, good point. I'm fine requiring those individuals to get a newer version if they want to compile BLIS.

**Comment by jdiamondGitHub** [comment] 2019-08-20 18:55
I'd love to get something as modern as 4.8.5. :)  We're currently stuck 
on 4.4, but I have hope that within a year 4.8.5 will become standard 
here.  A major consideration is that not all users have sudo access, and 
not all machines have access to package installers. Compiling gcc is not 
for the faint of heart, and it can easily brick your system.  (I've 
bricked 2 systems trying it.)  I've been in some very tight spots before 
around this.  There's a good reason to consider the needs of people 
trapped with system compilers, especially as blis gains wider use.

That being said, nothing wrong with having 2 versions of blis if you 
have a cool feature that needs modern gcc.

**Comment by devinamatthews** [comment] 2019-08-20 18:57
I tend to side with @fgvanzee because users will need somewhat up-to-date compilers (and assemblers!) in order to make use of the latest instruction set features and processor tunings anyways.

**Comment by jdiamondGitHub** [comment] 2019-08-20 19:00
Why?  The performance in blis comes from hand written assembly language 
kernels that do not require compiler support. I just request that you 
create an archive of the older version of blis so we can still use it in 
our company.  Not trying to tie your hands here - if you need it, you 
need it.  But it's all a slippery slope. For example, I know a lot of 
programmers that just can't wait to use the latest C++ features of the 
latest language version.  But that's not a friendly way to code, because 
it's the least portable.

**Comment by jdiamondGitHub** [comment] 2019-08-20 19:02
A lot of people don't even use gcc, so it's really about getting the 
right header. :)

**Comment by devinamatthews** [comment] 2019-08-20 19:05
What about binutils? If ld doesn't know what `vfmadd231pd` is then you're hosed. But in any case I think the modifications needed to use an older gcc are pretty minor, most of the configuration automaticness is for people who need the helping hand.

**Comment by fgvanzee** [comment] 2019-08-20 19:45
Le sigh. I'm torn between trying to unconditionally help out users in tough spots with really old compilers and drawing a line so that those users apply the pressure needed to get their sysadmins to update their software (which is almost always the right answer then the software in question is older than 3-4 years).

@jdiamondGitHub Version gcc 4.4 [is over a decade old](https://www.gnu.org/software/gcc/releases.html). If you really are stuck on software that old, man, I am really sorry. (in April 2009, BLIS did not exist. OpenBLAS likely did not exist, either--if it did, it was mere days old.) But at some point, we have to say, *No, you may not compile BLIS on your Hewlett-Packard 486 desktop that you purchased from CompUSA in 1996.* :)

I'll spend some time thinking about whether there might be a hack (and it will be kinda ugly) to support any weird systems where binutils is up to snuff but gcc is "too told" by `configure`'s standards. It would probably involve passing the gcc version information into the `Makefile` so that `make` can conditionally do something like `s/-march=haswell/-march=core-avx2/g`

**Comment by jdiamondGitHub** [comment] 2019-08-20 19:50
I feel your pain and just wanted to explain...

The main issue we have is the CentOS/RedHat system.  I don't claim to 
fully understand why, but RadHat by design keeps their software stack at 
least 5 years old.  One explanation I've heard is that they don't want 
to support developers, another is that they want to be able to provide 
something that's already well understood and safe. Either way, it keeps 
their costs down.  And then other linux variants inherit from Red Hat.

So it's far from the idea of having a 486 and no administrator 
privileges.   Red Hat, and it's derivatives, are practically a business 
standard.

**Comment by jdiamondGitHub** [comment] 2019-08-20 19:57
BTW, when we've complained about that, we're told "just build your 
system somewhere else and drop the binaries on Red Hat / etc". 
Unfortunately, we deal with a lot of software systems that need to be 
recompiled for a specific configuration, or even all the time. Does 
anyone know if Ubuntu has a variant that's professionally supported for 
business?  I'm not up on the Linux family tree.

**Comment by devinamatthews** [comment] 2019-08-20 19:59
"Professionally supported" as in you want to pay somebody money? If so, I think SUSE is probably the only other "business standard", but Ubuntu LTS releases are pretty easy to maintain.

**Comment by isuruf** [comment] 2019-08-20 19:59
@jdiamondGitHub, what's the glibc version on your system?

**Comment by jdiamondGitHub** [comment] 2019-08-20 20:02
Yep - that's what I mean.  I feel like one of the big reasons company 
pay for this isn't ease of use but responsibility. For example, if a 
security patch comes out and they don't install it and it hurts your 
business, you sue them. :)

For some reason, most companies I've been in don't use SUSE.  Maybe it's 
a marketing thing for large companies?

**Comment by devinamatthews** [comment] 2019-08-20 20:04
I think SCO technically still lets you pay them money 😄

**Comment by devinamatthews** [comment] 2019-08-20 20:05
But seriously I think Ubuntu has commercial support options too.

**Comment by jdiamondGitHub** [comment] 2019-08-20 20:05
The oldest I've found is 2.17.
But I'm hoping that it will be upgraded within a year...

**Comment by jdiamondGitHub** [comment] 2019-08-20 20:07
BTW, that system actually has 4.8.5 on it and represents the cutting 
edge of Red Hat. :)

**Comment by isuruf** [comment] 2019-08-20 20:08
I maintain blis packages for conda package manager at https://anaconda.org/conda-forge/blis/files
They support GLIBC based x86-64 linux distributions as old as CentOS 6. (glibc 2.14). They might work for you.

**Comment by jdiamondGitHub** [comment] 2019-08-20 20:11
BTW, I personally have access to systems where I can load modules and 
upgrade gcc as high as 6.0 - so when there are things that really are 
static, I can create blis binaries and somehow distribute them.  I'm 
also not against bifurcating here as well, saying, "here's a bunch of 
our products that simple won't run on Red Hat based systems."  But I 
have to be careful about that.  I never know when I might be told no.

Tell you what - let me figure out when Red Hat plans to upgrade and what 
version they are upgrading to.
- Jeff

**Comment by jdiamondGitHub** [comment] 2019-08-20 20:12
Thanks - that does sound like a good option.  And depending on what 
Field does, I may be able to mix and match source code if I need to 
upgrade something.

**Comment by fgvanzee** [comment] 2019-08-20 20:17
> So presumably the switchover happened sometime between those two versions.

BTW, I narrowed it down further. It appears that gcc transisitioned from the `-march=core-avx` style labels to `-march=sandybridge` style labels in version [4.9.0](https://gcc.gnu.org/onlinedocs/gcc-4.9.0/gcc/i386-and-x86-64-Options.html#i386-and-x86-64-Options). (Version [4.8.5](https://gcc.gnu.org/onlinedocs/gcc-4.8.5/gcc/i386-and-x86-64-Options.html#i386-and-x86-64-Options) was the last version to use the older labels.)

**Comment by jdiamondGitHub** [comment] 2019-08-20 23:31
Fantastic news!  I heard back from the OS team.  Turns out the challenge 
of a distro is to make sure that every single Linux app, utility, and 
script, in its latest, updated version, doesn't break any other Linux 
App, script, or hardware driver.  Red Hat tackles this exponential 
problem by only updating its software every 7-9 years!  While that has 
certainly caused us issues recently, the new version of Red Hat just 
dropped, and it's ALL NEW STUFF.  Within a year, as Red Hat percolates 
to the derivative Linuxes, we should all have gcc 8.2 instead of 4.8.5 ! :)

There may be some extra delay until customers upgrade, since it's a huge 
upgrade, but it means Field can probably update the gcc version in the 
near future.

**Comment by fgvanzee** [comment] 2019-08-21 17:27
Thanks for that update, Jeff. I've already finished the `corei7-avx`/`core-avx2` patch for pre-4.9.0 versions of gcc, so I'm going to go ahead and commit it. Eventually, I'll probably rip it out since it's kind of hideous by my coding standards. :) But in the meantime it may end up helping someone else.

**Comment by fgvanzee** [comment] 2019-08-21 17:41
I've committed e8c6281, which applies the aforementioned patch. People in @jdiamondGitHub's situation should be taken care of by this. (But, as @devinamatthews pointed out, if their `binutils` installation is not up-to-date, then no amount of patching on our side will help.)

**Comment by fgvanzee** [comment] 2019-08-21 17:42
@loveshack When you get a moment, please confirm that this fixes your original concerns.

**Comment by jeffhammond** [comment] 2019-08-21 20:50
I have a CentOS 6.6 machine specifically to understand the issues of
customers who are forced to use obsolete software. I’ve installed - both
using my own scripts and the RHEL repos specifically for this purpose - the
latest GCC tools, up to and including GCC git HEAD.

If somebody has Haswell gear but doesn’t upgrade to GCC and binutils that
supper AVX2, they are losing ~50% of performance. If people don’t care
about performance, why not use Netlib?  Or just compile BLIS with Ivy
Bridge settings and lose the 2x and not hit any issues with -march flags
and binutils.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by jdiamondGitHub** [comment] 2019-08-21 21:20
It's a huge problem because a lot of these people can't control the 
situation.  Red Hat supports a lot of large companies, and because of 
this has a lot of derivatives competing for the same market.  I think 
using AVX2 is the best they can hope for right now, but my concern was 
that the changes Field was making might retroactively break even AVX2 
for the older versions of gcc.  However, I think Field has found a way 
to support both versions.

Believe me, it wouldn't be the first time people lose 50% of performance 
due to an unrelated corporate decision. :)  If we knew someone who 
worked at Intel, and had connections to their performance software 
group, maybe they could come up with drop in source code to assemble the 
newer instructions?  Maybe something we could even add to blis, so blis 
isn't dependent on a compiler (or binutils) to produce the latest 
assembly instructions?

Ultimately, the question is how long people need derivatives of Red Hat 
older than version 8, and then how to create a longer term solution.
- Jeff

**Comment by devinamatthews** [comment] 2019-08-21 21:23
I'm just gonna put this out there that someone (not me!) could in theory write a back-end for the assembly macro-language that I added to produce hex instruction codes, at least for most things (not anything touching symbolic variables, etc.).

**Comment by jeffhammond** [comment] 2019-08-21 22:09
I install gcc and binutils without admin privileges. There is no “can’t
control”, only “can’t follow directions”.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by jeffhammond** [comment] 2019-08-21 22:11
Yes, I thought about the op code workaround to binutils. GASNet uses op
codes for atomics, presumably for similar reasons.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by fgvanzee** [comment] 2019-08-21 22:16
Am I the only one who thinks the built-in assembler idea is kind of nuts? At what point is it okay to just require a more recent binutils?

**Comment by dnparikh** [comment] 2019-08-21 23:05
Even better, we could starting writing BLIS in opcodes! ;)

**Comment by jdiamondGitHub** [comment] 2019-08-21 23:33
Well, that would be a great help - let's start posting some directions.  
Maybe even some scripts to make a user level install easy.  I've found 
installing gcc an incredible pain because you have to build so many sub 
projects, make sure all the libraries are visible to other libraries, 
leverage existing versions, build libc, etc.  Often I give up on targets 
where I have no package install access.

**Comment by jdiamondGitHub** [comment] 2019-08-21 23:58
Don't think of it as a built-in assembler.  Think of it as providing any 
easy way for a user to install a more recent assembler, or bin utils, or 
whatever bils needs (whatever form it takes - it could be a simple 
script).  But let's step back a sec...

All compilers are out of date (and I don't even use gcc), so the real 
question here is "how recent should they be"?  We're talking about a 
corporate policy that forces SW to be at least 7 years old. Is this an 
absolute or relative issue?  Once we're past 4.8.5, will you be good?   
And is this actually a big issue for blis, or did you just hit a minor 
hiccup here with the syntax of certain flags that changed around 4.9?    
Let's reverse the question: What's the minimum version of gcc and 
binutils you actually need?  And what for?  And then which operating 
systems can blis run on as a result? I see multiple issues here, but I'm 
guessing the primary technical one is keeping the blis kernels able to 
target the latest processors.  Don't view backwards compatibility as a 
generic policy - view it as a specific technical issue:  What are the 
concrete issues with specific versions of gcc or binutils?

If you tell us about your technical issues, we can help you with the 
broader decisions, such as: which OSes do those versions exclude, with 
how many users?  What might it mean for that community if blis supported 
those OSes?  Do other libraries (e.g. MKL, AMD, ARM) support that 
community?  How easy would it  be to upgrade those systems?  Could we 
provide binaries, etc?

I'm very happy to help you enable blis on massive corporate 
infrastructure, so you can focus on the part of development you love.

**Comment by devinamatthews** [comment] 2019-08-22 00:25
@jdiamondGitHub from the few times I've installed gcc from source, I imagine that most of your problems are solved by running the `contrib/download_prerequisites` script before configuring. Of course this step is poorly documented and rightly should be part of the build system by default but oh well.

**Comment by jdiamondGitHub** [comment] 2019-08-22 00:29
Thanks, I'll give it a try and see what happens.  :)

**Comment by loveshack** [comment] 2019-08-22 09:16
> (But,
> as @devinamatthews pointed out, if their `binutils` installation is
> not up-to-date, then no amount of patching on our side will help.)

The system binutils supports the same targets as the system compiler.  A
different binutils is relevant iff you use a more recent gcc for
micro-architecture support.  The rpm spec requires the devtoolset
binutils as well as the compiler (and I think the gcc rpm should do that
itself).

**Comment by loveshack** [comment] 2019-08-22 09:19
> If somebody has Haswell gear but doesn’t upgrade to GCC and binutils that
> supper AVX2, they are losing ~50% of performance. If people don’t care
> about performance, why not use Netlib?  Or just compile BLIS with Ivy
> Bridge settings and lose the 2x and not hit any issues with -march flags
> and binutils.

Or use the BLIS rpm packages, but perhaps I just shouldn't bother.

**Comment by loveshack** [comment] 2019-08-22 09:44
> All compilers are out of date (and I don't even use gcc),

??  I guess that at least explains the rubbish remarks.

> I'm very happy to help you enable blis on massive corporate 
> infrastructure, so you can focus on the part of development you love.

I've put significant effort into HPC support on EL6/7, though it's a
fairly unrewarding experience.  Could you please articulate exactly what
the problem is with the BLIS packages specifically (apart from the lack
of non-x86 dynamic dispatch)?  You'll probably even get reasonably
timely volunteer support.

If you need KNL/SKX support, you won't be on EL6 anyhow, but you can
disassemble the packages to see the avx512 instructions you seem to be
saying can't be generated on a pure RHEL system.  As I said, you don't
even need privileges if your system support is so bad.

[I'm not an apologist for Red Hat, as you can see on the Fedora devel
list.]

**Comment by jeffhammond** [comment] 2019-08-23 03:00
https://github.com/jeffhammond/HPCInfo/blob/master/buildscripts/gcc-release.sh
has been tested on a wide range of Linux systems including:
- behind corporate firewalls, with a proxy
- on Intel, AMD, ARM and IBM POWER systems
- on a range of distros, from CentOS 6 to Ubuntu 18

If you misuse make -j, it can brick your machine, because there’s a lot of
parallelism in GCC builds.

It does not support MacOS (use Homebrew), BSD (don’t care) or Blue Gene.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by devinamatthews** [comment] 2020-08-06 21:18
So, I think this is actually fixed... but with the lovely color commentary it's hard to tell. Please reopen if that is not the case.

**Closed by devinamatthews** 2020-08-06 21:18 UTC
