### ISSUE TITLE
blis make check crashes on completion on MacOS Mojave

### ISSUE THREAD

**Issue by jdiamondGitHub** [flame/blis#417] opened 2020-06-30 22:52 UTC
We've tried fresh git clones and builds of blis 0.7.0 (June 30th) on two different MacOS Mojave Macbook Pros.  One was built for Haswell (2015), the other for Sandybridge (2019).  In both cases, the build completed correctly, but make check ended in a segfault at the very end.  The output of make check showed that all tests were completed, and something segfaulted at the very end after dblat3.x finished.  This was confirmed by making the test in /blastest and then directly executing the isolated command: ./dblat3.x < input/dblat3.in

Segmentation fault: 11

Final output: blis_ztrsm_runu_cc                 100   100    16.32   3.08e-17   PASS

(This was on Apple Clang version 11.0.0 (clang-1100.0.33.17) Target: x86_64-apple-darwin18.7.0)

I was unable to create a functioning xcode project for blis (with an intent to debug), so I installed gdb 9.2 and tried to run it, but it seemed to run into the dreaded OS-X code signing permission issue!  No sign of this in the earlier clang run...

Reading symbols from dblat3.x...
(No debugging symbols found in dblat3.x)
(gdb) run < input/dblat3.in
Starting program: /Volumes/D/MacCode/BLIS/June30-2020/blastest/dblat3.x < input/dblat3.in
Unable to find Mach task port for process-id 11158: (os/kern) failure (0x5).
 (please check gdb is codesigned - see taskgated(8))

I do not believe blis has an issue, and only dblat3 seems to crash.  But this seems very consistent on Macs, and it didn't happen in older versions of blis.

I was wondering if anyone has experienced this, or if anyone has successfully ran blis in an XCode project?
Thanks everyone,
- Jeff

**Comment by devinamatthews** [comment] 2020-06-30 23:05
As one of the only Mac users in the bunch, I'll try to reproduce.

**Comment by devinamatthews** [comment] 2020-06-30 23:08
Confirmed on current master (b37634540fab0f9b8d4751b8356ee2e17c9e3b00). I'll try to debug.

**Comment by devinamatthews** [comment] 2020-06-30 23:20
@fgvanzee Looks like it is a bug in the gemmsup kernels (here `bli_dgemmsup_rv_haswell_asm_1x4`):

```asm
lea(mem(rsi, rsi, 2), rbp)         // rbp = 3*cs_c;
...
mov(var(k_iter), rsi)              // i = k_iter;
```

`rbp` is needed for the load from `k_iter` since it is on the stack. Solution: don't use `rbp` in kernels.

**Comment by fgvanzee** [comment] 2020-07-01 00:49
Thanks for looking into this, Devin.

> `rbp` is needed for the load from `k_iter` since it is on the stack. Solution: don't use `rbp` in kernels.

I don't quite follow this. It sounds like you're saying I'm trying to use a register that the compiler has already allocated. But why does `k_iter` not exist in memory only? Why does it have to occupy a register before the assembly region?

Also, can you venture a guess as to why I did not observe this error on Linux?

**Comment by devinamatthews** [comment] 2020-07-01 01:29
`k_iter` does only exist in memory (specifically the stack). However, in 64-bit mode `rbp` is used to address the stack. If you look at the generated assembly the load of `k_iter` is `movq   -0x58(%rbp), %rsi`

**Comment by devinamatthews** [comment] 2020-07-01 01:31
On linux, I think `-fomit-frame-pointer` is meaningful and causes `rsp` to be used instead. I'd have to check the assembly to be sure.

**Comment by devinamatthews** [comment] 2020-07-01 14:08
@jdiamondGitHub FYI to debug BLIS on macOS, just configure with `./configure -d noopt haswell` and then use the system `lldb`.

**Comment by fgvanzee** [comment] 2020-07-01 15:11
> On linux, I think `-fomit-frame-pointer` is meaningful and causes `rsp` to be used instead. I'd have to check the assembly to be sure.

Are you suggesting that Jeff's version of clang may not be honoring `-fomit-frame-pointer`?

And are you further suggesting that I shouldn't assume the compiler will recognize this option when writing kernels?

**Comment by devinamatthews** [comment] 2020-07-01 15:16
I don't know if it's a matter of not honoring the flag or a quirk of the platform ABI, but on macOS `rbp` is definitely used for stack addressing, even in optimized builds. I don't know if the same is true of *BSD.

**Comment by devinamatthews** [comment] 2020-07-01 15:16
Re the second question: Yes.

**Comment by fgvanzee** [comment] 2020-07-01 19:04
This [stackoverflow thread](https://stackoverflow.com/questions/43792447/assembled-c-appears-to-contain-superfluous-instructions) contained a link to Godbolt, which I began playing with. I was able to get clang 10.0 on darwin/x64_64 to honor `-fomit-frame-pointer`. (It doesn't support anything higher than clang 10.0.)

**Comment by devinamatthews** [comment] 2020-07-01 19:06
Apple clang is another matter entirely.

**Comment by fgvanzee** [comment] 2020-07-01 19:10
I don't have the emojis...

**Comment by devinamatthews** [comment] 2020-07-01 19:16
OK, apparently it does honor `-fomit-frame-pointer`, I just didn't realize that the flag **isn't in the kernels flags already**. Obviously if you're going to munge `rbp` then you have to explicitly add this.

**Comment by devinamatthews** [comment] 2020-07-01 19:17
BTW I checked adding it to the make_defs.mk for haswell and it works.

**Comment by fgvanzee** [comment] 2020-07-01 19:47
> OK, apparently it does honor `-fomit-frame-pointer`, I just didn't realize that the flag **isn't in the kernels flags already**. Obviously if you're going to munge `rbp` then you have to explicitly add this.

Having not looked into it myself, either, THAT is some egg that I'm happy to have on my face.

I'll submit a fix later today.

**Comment by fgvanzee** [comment] 2020-07-01 20:05
Also, how the hell did that code pass Travis in the first place?

**Comment by fgvanzee** [comment] 2020-07-15 18:52
@jdiamondGitHub FYI, this should be fixed. Please confirm for us when you are able to.

**Closed** 2020-08-06 22:23 UTC
