### ISSUE TITLE
out.sblat3 and out.dblat3 failing

### ISSUE THREAD

**Issue by robinchrist** [flame/blis#221] opened 2018-06-18 15:49 UTC
Hi,

Compiled using
clang version 6.0.0-svn322567-1~exp1 (branches/release_60)
Target: x86_64-pc-linux-gnu
Thread model: posix
Used config: Zen

Test output:
out.sblat3
```
 TESTS OF THE REAL             LEVEL 3 BLAS

 THE FOLLOWING PARAMETER VALUES WILL BE USED:
   FOR N                   0     1     2     3     5     9
   FOR ALPHA              .0   1.0    .7
   FOR BETA               .0   1.0   1.3

 ROUTINES PASS COMPUTATIONAL TESTS IF TEST RATIO IS LESS THAN   16.00

 RELATIVE MACHINE PRECISION IS TAKEN TO BE  1.2E-07

 SGEMM  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
           EXPECTED RESULT   COMPUTED RESULT
       1        .00000            .00000    
       2        .00000            .00000    
       3        .00000            .00000    
       4        .00000            .00000    
       5        .00000            .00000    
       6        .00000            .00000    
       7        .00000            .00000    
       8        .00000            .00000    
       9        .00000          -.386613E+10
      THESE ARE THE RESULTS FOR COLUMN   1
 ******* SGEMM  FAILED ON CALL NUMBER:
  15556: SGEMM ('N','N',  9,  2,  0, 1.0, A, 10, B,  1,  .0, C, 10).

 SSYMM  PASSED THE TESTS OF ERROR-EXITS

 SSYMM  PASSED THE COMPUTATIONAL TESTS (  1296 CALLS)

 STRMM  PASSED THE TESTS OF ERROR-EXITS

 STRMM  PASSED THE COMPUTATIONAL TESTS (  2592 CALLS)

 STRSM  PASSED THE TESTS OF ERROR-EXITS

 STRSM  PASSED THE COMPUTATIONAL TESTS (  2592 CALLS)

 SSYRK  PASSED THE TESTS OF ERROR-EXITS

 SSYRK  PASSED THE COMPUTATIONAL TESTS (  1944 CALLS)

 SSYR2K PASSED THE TESTS OF ERROR-EXITS

 SSYR2K PASSED THE COMPUTATIONAL TESTS (  1944 CALLS)

 END OF TESTS
```

out.dblat3
 ```
TESTS OF THE DOUBLE PRECISION LEVEL 3 BLAS

 THE FOLLOWING PARAMETER VALUES WILL BE USED:
   FOR N                   0     1     2     3     5     9
   FOR ALPHA              .0   1.0    .7
   FOR BETA               .0   1.0   1.3

 ROUTINES PASS COMPUTATIONAL TESTS IF TEST RATIO IS LESS THAN   16.00

 RELATIVE MACHINE PRECISION IS TAKEN TO BE  2.2E-16

 DGEMM  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
           EXPECTED RESULT   COMPUTED RESULT
       1        .00000          -.269730E+09
       2        .00000           .212787E+10
       3        .00000          -.216783E+10
      THESE ARE THE RESULTS FOR COLUMN   1
 ******* DGEMM  FAILED ON CALL NUMBER:
   9724: DGEMM ('N','N',  3,  2,  0, 1.0, A,  4, B,  1,  .0, C,  4).

 DSYMM  PASSED THE TESTS OF ERROR-EXITS

 DSYMM  PASSED THE COMPUTATIONAL TESTS (  1296 CALLS)

 DTRMM  PASSED THE TESTS OF ERROR-EXITS

 DTRMM  PASSED THE COMPUTATIONAL TESTS (  2592 CALLS)

 DTRSM  PASSED THE TESTS OF ERROR-EXITS

 DTRSM  PASSED THE COMPUTATIONAL TESTS (  2592 CALLS)

 DSYRK  PASSED THE TESTS OF ERROR-EXITS

 DSYRK  PASSED THE COMPUTATIONAL TESTS (  1944 CALLS)

 DSYR2K PASSED THE TESTS OF ERROR-EXITS

 DSYR2K PASSED THE COMPUTATIONAL TESTS (  1944 CALLS)

 END OF TESTS
```

Same error occurs with gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3.2)!

However, it works with the `generic` and `haswell` configuration, I assume this is an issue with the `zen` configuration!

**Comment by fgvanzee** [comment] 2018-06-18 16:48
@robinchrist Thanks for this bug report. It appears to be due to a bug in AMD's small matrix implementation (which is completely optional, but enabled by default). As a temporary workaround, you can comment out the following line in `config/zen/bli_family_zen.h`:
```
#define BLIS_ENABLE_SMALL_MATRIX
```
and then reconfigure/recompile normally. I plan on disabling this macro in `master` shortly until the issue is resolved.

@nisanthmpamd @kvaragan @pradeeptrgit : FYI, there appears to be a bug in your small matrix handling code for `zen`. (The bug does not manifest when small matrix handling is disabled.) It is reproducible with multiple compilers via:
```
./configure zen
make
make check
```
The failure manifests as described by Robin above, and on the command line as:
```
check-blastest.sh: At least one BLAS test failed. :(
check-blastest.sh: Please see out.* files for details.
Makefile:672: recipe for target 'checkblas' failed
```

**Comment by fgvanzee** [comment] 2019-01-28 18:11
I'm going to close this issue, for now.

@robinchrist Please re-open if this issue crops up again. (I'll be mindful of performing extra testing if/when I re-enable AMD's small matrix code.)

**Closed by fgvanzee** 2019-01-28 18:11 UTC
