### ISSUE TITLE
FAILURE in TRSM for very low input values

### ISSUE THREAD

**Issue by BhaskarNallani** [flame/blis#461] opened 2020-11-27 11:24 UTC
% --- trsm ---
%
% trsm m n                    3 3
% trsm operand params         llnn
%

% blis_<dt><op>_<params>_<stor>      m     n   gflops   resid      result
a:
4.940656e-324 0.000000e+00 0.000000e+00
0.000000e+00 4.940656e-324 0.000000e+00
0.000000e+00 0.000000e+00 4.940656e-324
b:
4.940656e-324 0.000000e+00 0.000000e+00
0.000000e+00 4.940656e-324 0.000000e+00
0.000000e+00 0.000000e+00 4.940656e-324
alpha
1.000000

b after:
inf  -nan  -nan
0.000000e+00  4.940656e-324  0.000000e+00
0.000000e+00  0.000000e+00  -inf

blis_dtrsm_llnn_rr                   3     3     0.00       -nan   FAILURE

b expected:

1  0  0
0  1  0
0  0  1

**Comment by BhaskarNallani** [comment] 2020-11-27 11:25
Injected these values into A, B @ ./blis/testsuite/src/test_trsm.c

**Comment by devinamatthews** [comment] 2020-11-27 14:56
@BhaskarNallani do you get the desired behavior from OpenBLAS, MKL, etc.?

**Comment by rvdg** [comment] 2020-11-27 14:59
Bhashar,

I suspect this problem comes from the fact that TRSM computes 1/x (where x is the diagonal element of the matrix) and then multiplies that result times values in the right-hand side.  If I am right, in computing 1/alpha, overflow happens for values this size, and that then translates to the “-inf”.

A fix for this would be to check x and branch if it is smaller than a certain threshold.  In that branch, you would then want to explicitly divide by x rather than computing 1/x and multiplying.

This would slow down the implementation considerably, I suspect.

Robert

**Comment by rvdg** [comment] 2020-11-27 15:01
I just checked this in octave.

If you set 
x = 4.940656e-324

Then

octave:2> 1/x
ans =  Inf
octave:3> x / x
ans =  1


I suspect the same happens in the TRSM call.

Robert

**Comment by BhaskarNallani** [comment] 2020-11-27 15:13
@rvdg  Yes. It is happening because a/b is done using a* (1/b) . This is to save the costly division operations but these are side effects. In trsm it is mixed with packing to optimized. We should think back now to move to a proper division operation.

@devinamatthews  
Openblas is behaving same has blis but MKL is giving correct output.

**Comment by devinamatthews** [comment] 2020-11-27 15:20
OK, second question: does this impact an important use case or is it more of a curiosity?

I ask because, if other packages (OpenBLAS is pretty widely used) also don't get it "correct" then this is frankly pretty low priority. Denormals are problematic all around and lots of high-performance software chokes on them.

**Comment by BhaskarNallani** [comment] 2020-11-27 15:42
When matrix size is big the division operation may not impact the performance but when matrixes are small this division might effect the performance. But do we need to worry about those small sizes at the cost of functionality?

**Comment by kvaragan** [comment] 2020-11-27 15:49
For the equation _AX = A,_ with _A_ containing very small values. The correct solution is _**I**_. I think that's what @BhaskarNallani meant by "correct". Coming to importance, basically we are doing some regression tests and discovered this bug. Therefore posting it here for any help we can get.

**Comment by devinamatthews** [comment] 2020-11-27 15:56
@kvaragan assuming this is a true regression please do a git-bisect and find where the bug was introduced.

**Comment by poulson** [comment] 2020-11-27 18:10
The need for specialized triangular solves when the diagonal values have
extremal values is reasonably well studied and does not require sacrificing
much performance, even in the worst case. And one could perform an initial
sweep over the diagonal as a cheap gate.

See this paper on a generalized version of TRSM with adjustable diagonal
shifts that compensates for overflow and underflow.

http://arxiv.org/pdf/1607.01477v2

**Comment by kvaragan** [comment] 2020-11-29 07:26
Thanks @poulson for the directions.

**Comment by fgvanzee** [comment] 2020-12-02 21:57
Is it the consensus here that we make this problem go away by using explicit division instructions within the microkernel?

**Comment by devinamatthews** [comment] 2020-12-02 22:00
My suggestion is to bench it unless/until someone demonstrates a real-world example of failure.

**Comment by devinamatthews** [comment] 2020-12-02 22:01
Edit: @kvaragan said "regression testing" so if this is in fact a regression then it should be fixed.

**Comment by rvdg** [comment] 2020-12-02 22:51
There are many options.

1) Leave it alone.  The TRSM is performance critical for HPL.  Even a slight slowdown may not be wanted.
2) Change to divisions in the microkernel.
3) Test before inverting to see if is is small.  If it is, call a microkernel that divides.  Otherwise proceed as is.

Orthogonal to this:  Make it a configure option.

If you want to look at how to implement option 3), I vaguely recall there is a place in LAPACK where this is explicitly done.  I thought it was in dpotf2, but I just looked and it is not there.

I am explicitly copying Greg Henry, who I suspect will know how to deal with this.

Robert

**Comment by fgvanzee** [comment] 2020-12-03 00:15
@devinamatthews My guess is that @kvaragan didn't actually mean regression testing, but rather stress testing. Very little about the `trsm` implementation has changed in the last few years.

**Comment by fgvanzee** [comment] 2020-12-03 00:23
> 1) Leave it alone.  The TRSM is performance critical for HPL.  Even a slight slowdown may not be wanted.

I like inertia. But I also like fixing problems and making people happy.

> 2) Change to divisions in the microkernel.

I am oppose using divisions in the kernels unconditionally. I did a quick test on my workstation, and this seems to result in a ~2% slowdown for medium-sized problems (more for small problems), which is less than I expected but still more than some may be willing to tolerate.

> 3) Test before inverting to see if is is small.  If it is, call a microkernel that divides.  Otherwise proceed as is.

I am opposed to maintaining two kernels at runtime, even if they are consolidated into the same source code.

> Orthogonal to this:  Make it a configure option.

I would be willing to make this a `configure` option. It wouldn't be *that* much work simply because we have very few `trsm` kernels that would need to be updated with cpp macro logic.

**Comment by rvdg** [comment] 2020-12-04 15:01
Am I to understand that BLIS gets wrong answers due to reciprocation of the diagonal in TRSM, and if it did not reciprocate the diagonal, then performance would drop but it’d get correct answers in this one test case?

               And what is the size of the test case? If it’s larger than exists normally in say a HPL run, then the third option below seems wisest: that way this would not impact performance of the “typical run”, but occasionally TRSM would go into slower, more careful code path when the problem size gets to be unruly.

               I think the optimization of reciprocation of the diagonals, when it can be used, is not such a bad idea. But I understand it can’t always work.

               LAPACK does have a specialized TRSM that uses scaling to prevent overflow, but only in the context of inverse iteration, and it’s notoriously slow (it’s actually only TRSV.)

Greg

**Comment by rvdg** [comment] 2020-12-04 15:15
Perhaps Field can repeat his message where he compared performance.

**Comment by fgvanzee** [comment] 2020-12-04 22:15
@BhaskarNallani @kvaragan Please see our configure-time solution in 7038bba.

As others have observed, ideally one would insert some intelligent logic that scans the triangular matrix diagonal and uses in-kernel divisions only if necessary, but that would seem to require additional kernels to manage at runtime or a conditional branch within the `gemmtrsm` kernel to select between one of two `trsm` code segments within the kernel function. While I am more comfortable with the latter possibility, I am not comfortable enough with it to implement it at this time.

**Comment by BhaskarNallani** [comment] 2020-12-05 16:09
@fgvanzee , Thank you for converging quickly into this solution. I verified that this is producing identity matrix as expected. 

But only testsuite is failing may because it is still expecting the correct output using old method for very low values. We can do the similar correction here too to pass the testsuite check.

**Comment by devinamatthews** [comment] 2020-12-05 16:39
@BhaskarNallani if I understand what you're saying correctly, the testsuite's reference values are incorrect for this example? I'll check on it.

**Comment by devinamatthews** [comment] 2020-12-05 16:50
@BhaskarNallani based on my reading of the trsv code, it should be OK for these values, and that is what is used to check trsm. Can you elaborate on your last comment?

**Comment by BhaskarNallani** [comment] 2020-12-07 05:36
@devinamatthews , It is failing at norm calculation and the residue going beyond the threshold value and testsuite throwing failure.

% --- trsm ---
%
% trsm m n                    3 3
% trsm operand params         llnn
%

% blis_<dt><op>_<params>_<stor>      m     n   gflops   resid      result
a
4.940656e-324 0.000000e+00 0.000000e+00
0.000000e+00 4.940656e-324 0.000000e+00
0.000000e+00 0.000000e+00 4.940656e-324

b
4.940656e-324 0.000000e+00 0.000000e+00
0.000000e+00 4.940656e-324 0.000000e+00
0.000000e+00 0.000000e+00 4.940656e-324

b after
1.000000e+00 0.000000e+00 0.000000e+00
0.000000e+00 1.000000e+00 0.000000e+00
0.000000e+00 0.000000e+00 1.000000e+00

t
8.323901e-01
2.714235e-01
4.345939e-01

v
8.323901e-01
2.714235e-01
4.345939e-01

w
1.000000e+00
0.000000e+00
0.000000e+00

z
1.000000e+00
0.000000e+00
0.000000e+00

norm
5.391063e-01


resid: 5.391063e-01
blis_dtrsm_llnn_rr                   3     3     0.00   5.39e-01   FAILURE

**Comment by fgvanzee** [comment] 2020-12-07 17:39
@devinamatthews I think what Bhaskar is saying is that he has hacked the testsuite to use arbitrary matrix inputs, and when fed the aforementioned pathological (denormal) values, the testsuite still fails.

**Comment by devinamatthews** [comment] 2020-12-07 19:33
@BhaskarNallani if you wouldn't mind, can you drill down a bit more and find out exactly which routine(s) in BLIS are having problems? From the results above I'm not sure where to head next. Agreed that your testsuite modification *should* pass after Fields patch.

@fgvanzee I got that.

**Comment by BhaskarNallani** [comment] 2020-12-22 07:34
For complex datatypes along with @fgvanzee fix added a saturation check to avoid a overflow when two sub norm numbers are multiplied as part of complex division. 

When 
x= a+ib
y= c+id
z=x/y
z.real   = ((a*c) + (b*d ))/(c2+d2) 
z.imag = ((b*c) - (a*d ))/(c2+d2) 

Here real multiplication in above equation can get overflow when inputs is a sub norm number.

**Comment by devinamatthews** [comment] 2020-12-22 14:51
The complex "level 0" macros do scale the numbers to avoid overflow of the denominator. The final results then *shouldn't* overflow, unless y is very small in magnitude and then overflow is of course unavoidable. I'm not sure if NaN propagation follows IEEE but who cares.

Or is the problem something else?

**Comment by BhaskarNallani** [comment] 2020-12-22 17:14
@devinamatthews , as said earlier the problem only coming for sub normal numbers which are mentioned in the above input data. Even though it is expensive added a complex division with saturation check in reference trsm kernels under the macro provided by Field.

**Comment by devinamatthews** [comment] 2020-12-22 17:24
Ah, in the microkernel. Good catch.

**Closed** 2020-12-24 16:15 UTC

**Comment by BhaskarNallani** [comment] 2020-12-24 16:22
The above fix provided by @fgvanzee helped to resolve issue in real data types (double/float) but for complex data types (native/induced methods) the similar fix need to be extended based on requirement under the macro BLIS_DISABLE_TRSM_PREINVERSION. Multiplications which are part of complex division requires a saturation check. Thank you all.

**Comment by fgvanzee** [comment] 2020-12-25 19:27
@BhaskarNallani Yes, and similarly I forgot to update the the reference gemmtrsm kernels, too. Those should also be updated to honor `BLIS_DISABLE_TRSM_PREINVERSION`. I'll dig into this after the holidays.

**Comment by fgvanzee** [comment] 2021-01-05 16:35
@BhaskarNallani Hopefully this latest commit addresses your concerns. Thanks again for the feedback.
