### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by tks2004** [flame/blis#263] opened 2018-10-03 14:20 UTC
During link phase, we get the following error:
/bin/ld:  amd-blis-1.0/lib/libblis-amd-1.0-zen.a(bli_util_tapi.o): unrecognized relocation (0x2a) in section `.text'
/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

**Comment by devinamatthews** [comment] 2018-10-03 14:27
What version (git commit or tag) of BLIS and what version of binutils and compiler are you using? OS information might help too.

**Comment by tks2004** [comment] 2018-10-03 14:53
blis-amd1.0, OS is RHEL7.4 with GNU 4.8.5 compiler. Any specific version of binutil to be used?

**Comment by devinamatthews** [comment] 2018-10-03 14:57
This type of error is usually associated with a linker that is too old for the compiler, but it looks like both are the default for your OS, right? What does `as --version` give?

**Comment by devinamatthews** [comment] 2018-10-03 15:05
I would still think it is some type of version incompatibility/bug. Does https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808181 help? Can you compile a simple "Hello World" program?

**Comment by tks2004** [comment] 2018-10-03 15:10
Yes. Hello world and other application works.

**Comment by devinamatthews** [comment] 2018-10-03 15:18
Interesting, can you send the output of `configure` and `make V=1`?

**Comment by devinamatthews** [comment] 2018-10-03 17:36
@tks2004 I didn't see the second half of your comment. If you consider this "fixed" we'll go ahead and close the issue.

**Comment by fgvanzee** [comment] 2018-10-18 21:55
It's been a couple weeks. I'm going to assume, based on @tks2004's last message, that the problem is fixed. Please re-open if needed.

**Closed by fgvanzee** 2018-10-18 21:55 UTC
