### ISSUE TITLE
ARM builds fail

### ISSUE THREAD

**Issue by fgvanzee** [flame/blis#170] opened 2018-03-13 21:11 UTC
On 03/12/18 09:27, Jacob Gorm Hansen wrote:
> On Sunday, March 11, 2018 at 11:22:40 PM UTC+1, Field Van Zee wrote:
>> Jacob,
>>
>> I have corrected the typos in 1442d06. Now, this may not be the *only* error standing in your way, but it definitely needed to get fixed. Please give it a try.
>
> It now gets a bit further, but ultimately dies with:
>
> Compiling obj/cortexa57/frame/base/bli_func.o ('cortexa57' CFLAGS for framework code)
> frame/base/bli_cpuid.c: In function "bli_cpuid_query_id":
> frame/base/bli_cpuid.c:54:17: error: "VENDOR_INTEL" undeclared (first use in this function); did you mean "VENDOR_ARM"?
>   if ( vendor == VENDOR_INTEL )
>                  ^~~~~~~~~~~~
>                  VENDOR_ARM
> compilation terminated due to -Wfatal-errors.
> make[1]: *** [Makefile:462: obj/cortexa57/frame/base/bli_cpuid.o] Error 1

Jacob: I've committed 1a303174, which hopefully addresses some of the issues. Please try it out and let me know the outcome.

**Comment by jacobgorm** [comment] 2018-03-14 12:52
Thank you!
it seems to be working for cortexa57 now. However, for cortexa15 (or a9) I am still getting misnamed kernel errors, and I had to apply this Makefile fix:

diff --git a/config/cortexa9/make_defs.mk b/config/cortexa9/make_defs.mk
index 684879da..8989dbd2 100644
--- a/config/cortexa9/make_defs.mk
+++ b/config/cortexa9/make_defs.mk
@@ -67,10 +67,10 @@ endif
 
 CKOPTFLAGS     := $(COPTFLAGS)
 
-ifneq ($(CC_VENDOR),gcc)
+ifeq ($(CC_VENDOR),gcc)
 CVECFLAGS      := -march=armv7-a
 else
-$(error gcc is required for this configuration.)
+$(error gcc is required for this configuration. $(CC_VENDOR))
 endif
 
 # Store all of the variables here to new variables containing the
  
Here is the make error I am getting for cortexa15:

configure: configured to build within top-level directory of source distribution.
make[1]: warning: -jN forced in submake: disabling jobserver mode.
make[1]: Entering directory '/home/jacob/dev/simplecnn/blis'
make[1]: *** No rule to make target 'obj/cortexa15/kernels/armv7a/3/bli_cgemm_armv7a_asm_2x2.o', needed by 'lib/cortexa15/libblis.a'.  Stop.
make[1]: *** Waiting for unfinished jobs....

**Comment by devinamatthews** [comment] 2018-03-14 16:18
@fgvanzee Turns out it is really easy to test ARM on Linux/x86:

```
dmatthews@annie:~/build/blis/aarch64$ sudo apt install gcc-aarch64-linux-gnu qemu
...
dmatthews@annie:~/build/blis/aarch64$ ~/src/blis/configure CC=aarch64-linux-gnu-gcc cortex-a57
...
dmatthews@annie:~/build/blis/aarch64$ make test_libblis.x
...
dmatthews@annie:~/build/blis/aarch64$ cp ~/src/blis/testsuite/input.* .
dmatthews@annie:~/build/blis/aarch64$ qemu-aarch64 -cpu cortex-a57 -L /usr/aarch64-linux-gnu/ test_libblis.x
...
```

We could probably put this in Travis as well. I don't know what happens with the "arm32" family since it will try to read /proc/cpuinfo... I guess we could fake up a cpuinfo file and use chroot for testing.

**Comment by fgvanzee** [comment] 2018-03-14 17:39
@jacobgorm Thanks for the feedback. Just to clarify, it sounds to me like you are claiming that your inlined patch fixes both `cortexa15` and `cortexa9`? Is my interpretation correct?

I'll apply the fix shortly.

**Comment by devinamatthews** [comment] 2018-03-14 17:40
@fgvanzee I'm working on a9 and a15 now. I'll pust a PR soon.

**Comment by devinamatthews** [comment] 2018-03-14 18:28
I guess we can leave this open until the fix is confirmed and merged to master.

**Comment by fgvanzee** [comment] 2018-03-14 19:28
@jacobgorm I assume we can close this now? Let us know if not.

**Comment by jacobgorm** [comment] 2018-03-14 22:01
Yes please go ahead and close the issue.

**Closed** 2018-03-14 22:43 UTC
