### ISSUE TITLE
Haswell indirectly blacklisted?

### ISSUE THREAD

**Issue by tonyskjellum** [flame/blis#214] opened 2018-06-03 13:56 UTC
Hi Field, cloned a new copy of BLIS this AM, so this is the latest hash(469727d).

Here is the configuration of this AVX2 capable Intel processor (Haswell E), but I am failing miserably.  Configuration generic works, however.

Trying to configure BLIS; generic works; by specifying either auto and haswell fails...
```
./configure auto
configure: detected Linux kernel version 3.19.0-32-generic.
configure: compiler search list is: gcc clang cc.
configure: using 'gcc' compiler.
configure: found gcc version 4.8 (maj: 4, min: 8, rev: ).
configure: checking for blacklisted configurations due to gcc 4.8.
configure: warning: gcc 4.8 does not support 'knl'; adding to blacklist.
configure: warning: gcc 4.8 does not support 'excavator'; adding to blacklist.
configure: warning: gcc 4.8 does not support 'zen'; adding to blacklist.
configure: warning: gcc 4.8 does not support 'skx'; adding to blacklist.
configure: found assembler ('as') version 2.24 (maj: 2, min: 24, rev: ).
configure: checking for blacklisted configurations due to as 2.24.
configure: configuration blacklist:
configure:   knl excavator zen skx
configure: reading configuration registry...done.
configure: needed to indirectly blacklist additional configurations:
configure:   haswell  <----- this seems bad
configure: determining default version string.
configure: found '.git' directory; assuming git clone.
configure: executing: git describe --tags.
configure: got back 0.3.2-45-g469727d.
configure: truncating to 0.3.2-45.
configure: starting configuration of BLIS 0.3.2-45.
configure: configuring with official version string.
configure: found shared library .so version '0.0.0'.
configure:   .so major version: 0
configure:   .so minor.build version: 0.0
configure: automatic configuration requested.
configure: hardware detection driver returned 'haswell'.
configure: checking configuration against contents of 'config_registry'.
configure: 'auto-detected configuration '' is NOT registered!   <--------------- empty string here
configure: 
configure: *** Cannot continue with unregistered configuration ''. ***
configure: 
```
Checked the processor type; has AVX and AVX2  
```
tony@kylo-ren:~/Sandbox/FLAME-BLIS/blis$ gcc -march=native -Q --help=target|grep march
  -march=                               core-avx2
tony@kylo-ren:~/Sandbox/FLAME-BLIS/blis$ sudo dmidecode|grep -i intel
        Manufacturer: Intel
        Version: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
   [aka Formerly Haswell E]
```
Any advice appreciated.

Thank you,
Tony Skjellum

**Comment by fgvanzee** [comment] 2018-06-03 20:27
@tonyskjellum While I look into this issue, I thought I would mention that your compiler is quite old and barely supported by BLIS. I recommend upgrading to gcc 5.4 or newer, if you can.

**Comment by tonyskjellum** [comment] 2018-06-03 20:50
Will do re gcc 

Anthony Skjellum, PhD
205-807-4968

**Comment by fgvanzee** [comment] 2018-06-03 21:15
@tonyskjellum I've done some digging, and it appears that `configure` is behaving exactly as designed. The problem is very subtle and nuanced. Let me explain.

First, we have this concept of blacklisting sub-configurations. This is done so that, for example, when you build the multi-configuration `x86_64` target on a system that does not know how to emit SkylakeX (AVX512) object code, it doesn't try. In that case, the unsupported sub-configurations are pruned out and the build system only builds what it knows how to build.

The next thing to notice is that BLIS allows certain sub-configurations to be defined as requiring other sub-configurations' kernels. This was done so that similar microarchitectures could share kernels. For example, we define the `haswell` sub-configuration as requiring that both `haswell` and `zen` kernel sets be made available whenever the `haswell` sub-configuration is chosen (`haswell` uses the level-3 kernels written for `zen`). In general, this creates the rather problematic opportunity for partially-supported sub-configurations. Suppose for a moment that we don't know anything about `haswell` and `zen` kernels. If the `zen` sub-configuration (which was created hand-in-glove with the `zen` kernel set) was blacklisted due to compiler version issues, we would understandably want to also (indirectly) blacklist `haswell` since it requires `zen` kernels. This is how it's supposed to work in the abstract.

The problem in our case is that while we happen to know that `zen` kernels can be treated indistinguishably from `haswell` kernels, the build system is making a stronger (and safer) assumption that if the compiler doesn't support compiler flags written into the `zen` sub-configuration, then there must be something about the *specific assembly code* in those `zen` kernels that the compiler does not support (since the two were written hand-in-glove).

This implicit assumption is the issue. It just so happens that gcc 4.8 does not support the `zen` compiler flags, even with the backwards compatible workaround I have in place, but it *does* support `haswell` compiler flags. However, the `configure` script is blindly following the rules and thus throws up red flags as a result.

If you would like a hackish workaround, I can give you one. But ideally you would upgrade your compiler and the issue would be solved that way instead. Let me know how you want to proceed.

**Comment by devinamatthews** [comment] 2018-06-03 21:42
I think it would certainly behoove us to have `haswell` work in this and similar circumstances.

**Comment by fgvanzee** [comment] 2018-06-03 22:26
@devinamatthews The simplest option would be to stop supporting gcc 4.x, but I suspect you had something more accommodative in mind.

The next simplest option would be to relocate and rename the level-3 `zen` kernels to the `haswell` kernel set. It's somewhat of a circumstantial fix, but it works for now.

**Comment by fgvanzee** [comment] 2018-06-03 22:35
I'm beginning to think that the whole concept of indirect blacklisting was misguided. I may have failed to appreciate some of the implicit assumptions behind sub-configurations sharing kernel sets juuuust long enough to implement an unnecessary feature.

**Comment by devinamatthews** [comment] 2018-06-03 22:37
Haswell and zen may share code but I would think they would use their own flags for kernels, thus no need to blacklist.

**Comment by fgvanzee** [comment] 2018-06-03 22:45
@devinamatthews Precisely. BLIS's configuration system already uses the targeted sub-configuration's compilation flags even when borrowing the kernel set of another configuration. If we set up sub-configuration `foo` to use `bar`'s kernels, that implies that we expect that the `bar` kernel set to be compile-able using `foo`'s sub-configuration and its compiler flags. Thus, this doesn't really beg the need for indirect blacklisting.

I think I can disable indirect blacklisting while leaving the code that implements it intact, in case we realize it is needed after all.

**Comment by fgvanzee** [comment] 2018-06-03 23:11
@tonyskjellum This should be fixed now in 7a207e8, even without a compiler upgrade. In fact, if you haven't upgraded yet, perhaps you could give it a try for us to make sure the fix works as intended.

**Comment by tonyskjellum** [comment] 2018-06-03 23:33
Upgrading to GCC/G++ 5.5 solved the problem ; then I saw your memo.   It works fine with GCC 5.5 as I know you know.

Then I reverted to 4.8 (changes of soft links); cleaned, configured; now also works with GCC/G++ 4.8 in haswell config.

Tony

**Closed** 2018-06-03 23:37 UTC

**Comment by fgvanzee** [comment] 2018-06-03 23:52
Great, thanks Tony.
