### ISSUE TITLE
BLIS gemm microkernel segfaults if buffers are not 32 byte-aligned

### ISSUE THREAD

**Issue by ivan23kor** [flame/blis#591] opened 2021-12-23 18:23 UTC
Hi, I am trying to call native sgemm microkernels and observe segfault in the microkernels.
I am compiling [this code](https://gist.github.com/ivan23kor/b3db676728bbc9fe1188c964ba57db31) with `gcc blis_gemm_ukr_align_error.c -lblis -lm -lpthread`.
The issue only happens if the buffers are not aligned to 32 bytes.

Affected architectures are at least Haswell, Zen2 and skx.
It does not happen on the same Haswell with Mac OS and clang-13.

This issue might be related to #550.

**Comment by devinamatthews** [comment] 2021-12-23 19:02
@ivan23kor the microkernels expect a very specific layout for the packed A and B buffers, which can include alignment restrictions. The kernels typically used aligned load instructions e.g. `vmovapd` so using an improperly aligned buffer can indeed lead to a segfault.

**Comment by ivan23kor** [comment] 2021-12-23 20:31
I see.

Then what about this line from the [KernelsHowTo](https://github.com/flame/blis/blob/master/docs/KernelsHowTo.md#implementation-notes-for-gemm):

> Alignment of a1 and b1. By default, the alignment of addresses a1 and b1 are aligned only to sizeof(type). If BLIS_POOL_ADDR_ALIGN_SIZE is set to some larger multiple of sizeof(type), such as the page size, then the first a1 and b1 micropanels will be aligned to that value, but subsequent micropanels will only be aligned to sizeof(type), or, if BLIS_POOL_ADDR_ALIGN_SIZE is a multiple of PACKMR and PACKNR, then subsequent micropanels a1 and b1 will be aligned to PACKMR * sizeof(type) and PACKNR * sizeof(type), respectively.

**Comment by devinamatthews** [comment] 2021-12-23 20:52
`BLIS_POOL_ADDR_ALIGN_SIZE` is definitely a multiple of `PACKNR` (`PACKMR` is irrelevant in this case) since they're both powers of two. @fgvanzee any other comments?

**Comment by devinamatthews** [comment] 2021-12-23 21:01
Also note that `BLIS_POOL_ADDR_ALIGN_SIZE` is by default 4kB (i.e. page) alignment.

**Comment by fgvanzee** [comment] 2021-12-23 23:14
It seems that the KernelsHowTo (at the very least) needs to be updated to clean up that second sentence, which is probably outdated and definitely misleading.

But yes, Devin is right: BLIS defaults to using a `BLIS_POOL_ADDR_ALIGN_SIZE` of 4096 bytes. Until I can untangle what the *actual* constraints are, @ivan23kor, it would be best to continue to align the start of your pack buffers to 4096 bytes, just to be safe.

**Comment by devinamatthews** [comment] 2022-01-11 00:49
Closing since this is the expected behavior.

**Closed by devinamatthews** 2022-01-11 00:49 UTC

**Comment by fgvanzee** [comment] 2022-02-15 21:04
@ivan23kor I've cleaned up the alignment language in `KernelsHowTo.md` in ee9ff98. Thanks again for your feedback.

**Comment by ivan23kor** [comment] 2022-02-16 02:07
@fgvanzee looks good now, thanks!
