### ISSUE TITLE
Compiling BLIS on Intel Xeon Phi 7210 knl is failing with the error pasted below.

### ISSUE THREAD

**Issue by gareevroman** [flame/blis#167] opened 2018-02-19 06:37 UTC
Hi,

Compiling BLIS on Intel Xeon Phi 7210 knl is failing with the error pasted below.

I am doing the following:
./configure --enable-threading=openmp -path=/users/rgareev/roman/Frameworks/build/BLIS knl
make

Generating monolithic blis.h.....................................................................................................................................................................................................................................................................................................................................................................................................................................................
Generated include/knl/blis.h
Compiling obj/knl/config/knl/bli_cntx_init_knl.o ('knl' CFLAGS for config code)
Compiling obj/knl/kernels/knl/1m/bli_packm_knl_asm_24x8.o ('knl' CFLAGS for kernels)
kernels/knl/1m/bli_packm_knl_asm_24x8.c:35:31: fatal error: bli_avx512_macros.h: No such file or directory
compilation terminated.
make: *** [obj/knl/kernels/knl/1m/bli_packm_knl_asm_24x8.o] Error 1

Thanks,
Roman

**Comment by devinamatthews** [comment] 2018-02-19 17:37
Hi Roman,

This should be fixed with 5d03b6e. Please let us know how the performance is, especially if you run in both cache and flat memory modes. I have had mixed experiences with cache mode...

Devin

**Comment by fgvanzee** [comment] 2018-02-19 17:38
Thanks Devin. I haven't looked closely at `bli_avx512_macros.h`, but if it ends up being used for future microarchitectures, another solution would be to move it into `frame/include`, or somewhere else outside of `kernels/skx`. That would result in it being pulled into the monolithic/flattened `blis.h` prior to complication.

**Comment by gareevroman** [comment] 2018-02-19 19:16
Hi Devin,

> This should be fixed with 5d03b6e.

5d03b6e fixes this. However, it produces a new error:
./configure --enable-threading=openmp -path=/users/rgareev/roman/Frameworks/build/BLIS knl
…
make
Generating monolithic blis.h.....................................................................................................................................................................................................................................................................................................................................................................................................................................................
Generated include/knl/blis.h
Compiling obj/knl/config/knl/bli_cntx_init_knl.o ('knl' CFLAGS for config code)
Compiling obj/knl/kernels/knl/1m/bli_packm_knl_asm_24x8.o ('knl' CFLAGS for kernels)
kernels/knl/1m/bli_packm_knl_asm_24x8.c:105:6: error: conflicting types for ‘bli_dpackm_knl_asm_8xk’
 void bli_dpackm_knl_asm_8xk
      ^
compilation terminated due to -Wfatal-errors.
make: *** [obj/knl/kernels/knl/1m/bli_packm_knl_asm_24x8.o] Error 1

>  Please let us know how the performance is, especially if you run in both cache and flat memory modes. I have had mixed experiences with cache mode…

Sure.

Thanks,
Roman

**Comment by devinamatthews** [comment] 2018-02-19 19:18
Why is `-Wfatal-errors` enabled? Just turn that flag off, as the compiler is only complaining about `restrict` consistency in the prototype which has no binary impact.

**Comment by fgvanzee** [comment] 2018-02-19 20:11
I enabled `-Wfatal-errors` for all configurations in `common.mk` so that compilation stops after the first compiler error. This is useful when lots of errors are reported; it lets you focus on the first error, since that is usually the most important one.

It's not clear to me how `-Wfatal-errors` can pose a nuisance since it would appear to only limit the reported errors to one when there are non-zero errors.

**Comment by devinamatthews** [comment] 2018-02-19 20:13
Ah, I was thinking of `-Werror`. I only get a warning on my system. I will fix this at some point, but it should just be a matter of fiddling with the `restrict`s.

**Comment by fgvanzee** [comment] 2018-04-04 22:48
@gareevroman Would you care to share your real name so I can acknowledge your contribution in our upcoming 0.3.1 release announcement? No worries if you'd rather stay anonymous.

PS: I assume this issue was resolved? If you're still having trouble, please let us know.

**Comment by gareevroman** [comment] 2018-04-07 08:16
> Would you care to share your real name so I can acknowledge your contribution in our upcoming 0.3.1 release announcement? 

Sorry for the late reply. My real name is Roman Gareev. Please use it.

> PS: I assume this issue was resolved? If you're still having trouble, please let us know.

I managed to fix it in case of the BLIS 0.2.2. To do it, I changed the compiler from gcc 4.9.3 to icc 17.0.4 and commented out the following lines of BLIS/frame/base/bli_gks.c:

    --- a/frame/base/bli_gks.c
    +++ b/frame/base/bli_gks.c
    @@ -360,9 +360,9 @@ void bli_gks_register_cntx
            blksz_t* restrict nr = bli_cntx_get_blksz( BLIS_NR, gks_id_nat );
            blksz_t* restrict kr = bli_cntx_get_blksz( BLIS_KR, gks_id_nat );
 
    -       e_val = bli_check_valid_mc_mod_mult( mc, mr ); bli_check_error_code( e_val );
    -       e_val = bli_check_valid_nc_mod_mult( nc, nr ); bli_check_error_code( e_val );
    -       e_val = bli_check_valid_kc_mod_mult( kc, kr ); bli_check_error_code( e_val );
    +       //e_val = bli_check_valid_mc_mod_mult( mc, mr ); bli_check_error_code( e_val );
    +       //e_val = bli_check_valid_nc_mod_mult( nc, nr ); bli_check_error_code( e_val );
    +       //e_val = bli_check_valid_kc_mod_mult( kc, kr ); bli_check_error_code( e_val );
     #ifndef BLIS_RELAX_MCNR_NCMR_CONSTRAINTS
            e_val = bli_check_valid_mc_mod_mult( mc, nr ); bli_check_error_code( e_val );
            e_val = bli_check_valid_nc_mod_mult( nc, mr ); bli_check_error_code( e_val );


Otherwise, BLIS produces the following error during the execution of the bli_dgemm:

libblis: ../../BLIS/frame/base/bli_gks.c (line 363):
libblis: 
libblis: Aborting.
Aborted 

In case of the BLIS 0.3.1, BLIS produces a segmentation fault during the execution of the bli_dgemm even if the lines are commented out. I haven’t managed to find the reason yet. 

Thanks,
Roman Gareev

**Comment by fgvanzee** [comment] 2018-04-09 17:35
@gareevroman Sorry you are still having trouble. I'd like to look into this, but first could you tell me that in the case of 0.3.1, are you using a downloaded release, or a git clone? If you are using a clone, the exact commit hash number would be helpful. Also, please copypaste how you are executing `configure`.

**Comment by loveshack** [comment] 2018-04-10 16:31
[I should have spotted this before as I'd been pushing KNL.]
The broken tests in 0.3.1 for both KNL and the general x86_64 configuration are fixed in the git dev branch as far as I can tell. They work for me on KNL and Haswell, anyhow.

I think GCC 5 should work, but GCC 6 definitely will (using the devtoolset-6-gcc package if you happen to be on RHEL or a clone).

**Comment by fgvanzee** [comment] 2018-04-10 16:34
@loveshack Thanks for chiming in. Is that to say that you were previously observing the same error that Roman reported on Feb 19?

**Comment by loveshack** [comment] 2018-04-10 18:21
> @loveshack Thanks for chiming in. Is that to say that you were
> previously observing the same error that Roman reported on Feb 19?

I don't think so, but I was previously trying with KNL before it was in
a release, and I think I was using gcc 6.

I just wanted to note that you need post-release code, which works to
the extent I've tested it, specifically on KNL.

**Comment by fgvanzee** [comment] 2018-04-10 18:27
> I just wanted to note that you need post-release code, which works to the extent I've tested it, specifically on KNL.

@gareevroman As Dave suggests, you should try out the latest commits if you haven't already. If you still have issues, please describe them here and we can work towards a resolution.

**Comment by gareevroman** [comment] 2018-04-11 08:02
> @gareevroman Sorry you are still having trouble. I'd like to look into this, but first could you tell me that in the case of 0.3.1, are you using a downloaded release, or a git clone? If you are using a clone, the exact commit hash number (first eight digits is fine) would be helpful. Also, please copypaste how you are executing configure.

I used a git clone with bd0276752ccdd56ff897b1a5ae022f2ffe6e0b38 hash number.

> EDIT: Sorry, for some reason I thought this issue was thought to be fixed, but that you subsequently ran into additional trouble. Looking more closely, it seems that we never reached a resolution on your original problem. Are you still configuring the same as above?

Yes, I'm configuring the same as above.

> @gareevroman As Dave suggests, you should try out the latest commits if you haven't already. If you still have issues, please describe them here and we can work towards a resolution.

I also get a segmentation fault during the execution of the bli_dgemm in case of the 388f64d6ade14caa4a6c286845ad2d565378b2bb and gcc 6. For some reason, the BLIS 0.2.2 doesn't cause it. I'll try to bisect the bug on weekend.

Thanks,
Roman Gareev

**Comment by fgvanzee** [comment] 2018-04-11 16:38
@gareevroman It's probably not related, but I want to point out that `-path` is not a valid argument to `configure`. It should be `-p <path>` or `--prefix=<path>`. When I try using `-path`:
```
./configure --enable-threading=openmp -path=/home/field knl
```
I get `configure` output that includes:
```
configure: using install prefix 'ath=/home/field'.
```
which granted is not the ideal response. (Ideally, configure would exit with a fatal error message.)

**Comment by fgvanzee** [comment] 2018-04-11 17:01
@gareevroman A few comments:
1. I don't have access to gcc 4.x, but I do have gcc 5.4, gcc 7.1, and icc 17.0.4. I cannot reproduce the "conflicting types" compilation error with any of them. Are you still getting this error with the most recent commits?
2. It sounds like you got past that error, because you more recently mentioned a segmentation fault when calling `bli_dgemm()`. Can you elaborate on how you were able to build successfully. What happens when you run `make check` after your successful build? How you are running `bli_dgemm()`? If the former is successful, then it may be a problem with how you are invoking `bli_dgemm()`.
3. Using a recent commit on the `dev` branch (f56481e) I did not observe any segmentation faults while running `make check` with any of the compilers listed above.

I'm confident we'll get to the bottom of this, it may just take some time.

**Comment by loveshack** [comment] 2018-04-12 16:05
I wouldn't expect gcc 4.9 to be a good compiler to use as it's the first
version with any support for avx512.  Perhaps configure should blacklist
it if the failure is with current source and a properly cleaned-out
directory.  (I've fallen foul of not cleaning up the test code after an
update that apparently didn't fix errors; there's probably a missing
make dependency I'd forgotten to look at.)

**Comment by loveshack** [comment] 2018-04-25 11:39
For what it's worth, I noticed libxsmm disabled gcc 4.9 for avx512 <https://github.com/hfp/libxsmm/commit/47f5a382f39ed340ea8cc20239aaa38cda742eb3>.  Perhaps BLIS should do the same if avx512 isn't excluded by the binutils version anyhow.

**Comment by fgvanzee** [comment] 2018-04-30 17:53
@gareevroman I cannot reproduce any issues when targeting `knl` on Knights Landing hardware. If you are still having trouble, please let us know. Otherwise, I'll assume the issue has been fixed.

**Closed** 2018-05-15 17:07 UTC
